Release for mixed session
kobiton/docs pull request #202
Opened 2024-04-08 07:58 UTC by tungmhoang

### Summary

- Update content of mixed session guide. Preview link: http://10.2.7.208/manual-testing/start-a-mixed-session

### Related PRs, issues, or features (optional)

- https://kobiton.atlassian.net/browse/KOB-39139

### Metadata

- [x] Adds new file(s)
- [x] Edits existing file(s)
- [x] Removes file(s)

### PR contributor checklist

- [x] My PR follows the [Kobiton Docs contributor guidelines](https://github.com/kobiton/docs/blob/main/CONTRIBUTE.adoc), meaning:

    - My content contains correct spelling and grammar.
    - My directories and files are [named](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#directory-and-file-names) and [structured](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#directory-structure) correctly.
    - My style and voice follows the [Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/brand-voice-above-all-simple-human).
    - I added all new pages to their section's [`nav.adoc` file](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#configure-navigation-in-navadoc).
    - I removed all localizations (like `en-us`) from my URLs.

2024-05-08 18:33 UTC, erincbailey requested changes
I was not able to review this in the "preview" site - but I looked through the changes. I made a couple of wording suggestions. Then you can publish. Thank you!

2024-05-08 18:33 UTC, erincbailey commented on docs/modules/automation-testing/pages/start-a-mixed-session.adoc
> +A mixed session is where you can use the feature of a manual session to observe what is happening when running an Appium automation script.
A mixed session allows you to observe what occurs during the execution of an Appium automation script through a manual session.

2024-05-08 18:33 UTC, erincbailey commented on docs/modules/automation-testing/pages/start-a-mixed-session.adoc
> +* Manual actions in a mixed session is not yet available when a Basic Appium 2 script is running.
Performing manual actions in a mixed session is not supported for Basic Appium 2 script execution.

2024-05-08 18:33 UTC, erincbailey commented on docs/modules/automation-testing/pages/start-a-mixed-session.adoc
> +* A mixed session counts as 1 parallel test session, although it includes a manual and an automation session.
A mixed session counts as 1 parallel test session, even though it includes both a manual and an automation session.

2024-05-14 09:01 UTC, tungmhoang commented
@erincbailey please approve the PR so I can merge

2024-05-14 09:55 UTC, erincbailey approved these changes
approved

2024-05-14 09:55 UTC, merged