iOS voice over page deleted. Table of Content updated. One internal reference removed
kobiton/docs pull request #220
Opened 2024-05-26 01:28 UTC by Hikkigaya

The iOS voice-over page was deleted. Table of Contents updated. One internal reference removed from Devlice Controls section.

### Summary
The iOS voice-over page was deleted. Table of Contents updated. One internal reference removed from Devlice Controls section.

### Related PRs, issues, or features (optional)

- [N/A]

### Metadata

- [ ] Adds new file(s)
- [x] Edits existing file(s)
- [x] Removes file(s)

### PR contributor checklist

- [x] My PR follows the [Kobiton Docs contributor guidelines](https://github.com/kobiton/docs/blob/main/CONTRIBUTE.adoc), meaning:

    - My content contains correct spelling and grammar.
    - My directories and files are [named](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#directory-and-file-names) and [structured](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#directory-structure) correctly.
    - My style and voice follows the [Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/brand-voice-above-all-simple-human).
    - I added all new pages to their section's [`nav.adoc` file](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#configure-navigation-in-navadoc).
    - I removed all localizations (like `en-us`) from my URLs.

2024-05-26 01:35 UTC, Hikkigaya commented on docs/modules/manual-testing/pages/device-controls.adoc
> -
This was the section, I removed, I'm not really why the GitHub is showing the entire page as edited

2024-05-29 17:01 UTC, erincbailey commented
@tungmhoang Can you please review this one?

2024-06-12 04:01 UTC, tungmhoang approved these changes
Added a commit to change the redirection to a page under DLM section. Also added the limitation with voiceover there.

2024-06-12 04:05 UTC, tungmhoang commented
@erincbailey Please review the changes I just made to redirect the voiceover page to a page under DLM section. Use this link to see the redirection: http://10.2.7.208/devices/local-devices/configure-ios-voiceover

2024-06-12 04:07 UTC, tungmhoang commented
> @erincbailey Please review the changes I just made to redirect the voiceover page to a page under DLM section. Use this link to see the redirection: http://10.2.7.208/devices/local-devices/configure-ios-voiceover

2024-06-12 09:41 UTC, erincbailey requested changes

2024-06-12 09:41 UTC, erincbailey commented on docs/modules/device-lab-management/pages/ios-devices/index.adoc
> +* Perform Voiceover is no longer supported due to a change in iOS's Bluetooth protocol. We will let you know when this feature is supported again.
Capitalize it VoiceOver instead of Voiceover per https://www.apple.com/voiceover/info/guide/_1121.html

2024-06-13 11:42 UTC, erincbailey approved these changes
approved

2024-06-14 08:00 UTC, merged