Two new pages added with images and code blocks
kobiton/docs pull request #245
Opened 2024-06-25 15:59 UTC by Hikkigaya

### Summary

Two new pages added with images and code blocks

### Related PRs, issues, or features (optional)

- 244

### Metadata

- [x] Adds new file(s)
- [x] Edits existing file(s)
- [ ] Removes file(s)

### PR contributor checklist

- [x] My PR follows the [Kobiton Docs contributor guidelines](https://github.com/kobiton/docs/blob/main/CONTRIBUTE.adoc), meaning:

    - My content contains correct spelling and grammar.
    - My directories and files are [named](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#directory-and-file-names) and [structured](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#directory-structure) correctly.
    - My style and voice follows the [Microsoft Style Guide](https://learn.microsoft.com/en-us/style-guide/brand-voice-above-all-simple-human).
    - I added all new pages to their section's [`nav.adoc` file](https://github.com/kobiton/docs/blob/main/CONTRIBUTING.md#configure-navigation-in-navadoc).
    - I removed all localizations (like `en-us`) from my URLs.

2024-07-26 09:07 UTC, tungmhoang commented
@erincbailey you can review this PR at:
- http://10.2.7.208/integrations/applitools-eyes/applitools-eyes-integration
- http://10.2.7.208/automation-testing/scripting/run-applitools-eyes-script
- http://10.2.7.208/session-explorer/manage-sessions

2024-07-26 09:08 UTC, tungmhoang approved these changes

2024-07-26 14:31 UTC, erincbailey requested changes
Just two minor comments in the pages.
Plus, should the images be left justified? Sampling other pages - they are left justified. Please confirm.

2024-07-26 14:31 UTC, erincbailey commented on docs/modules/integrations/pages/applitools-eyes/applitools-eyes-integration.adoc
> += Enable Applitools Eyes integration
Remove "Enable" from title. Looking at all the other integration pages, this isn't part of the title

2024-07-26 14:31 UTC, erincbailey commented on docs/modules/automation-testing/pages/scripting/run-applitools-eyes-script.adoc
> +At the time of writing, the final test script would look like the below:
Remove "At the time of writing," and make the capital "The final..."
(The phrase is not needed and instills doubt. All tech docs are valid as of the time of writing.)

2024-07-26 16:57 UTC, tungmhoang commented
@erincbailey feedback addressed. Updated images to be left justified as well. @Hikkigaya please note that images should be left-justified, unless it is a mobile screenshot. Mobile screenshot just looks weird if left-justified.

2024-07-27 04:39 UTC, Hikkigaya commented
> @erincbailey feedback addressed. Updated images to be left justified as well. @Hikkigaya please note that images should be left-justified, unless it is a mobile screenshot. Mobile screenshot just looks weird if left-justified.

Noted

2024-07-29 09:36 UTC, erincbailey approved these changes
approved

2024-07-29 09:56 UTC, merged